<a href="https://colab.research.google.com/github/sak1b0/proteiNN/blob/master/Hot_String1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np

url_train='https://raw.githubusercontent.com/sak1b0/proteiNN/master/train_formatted.csv'
url_test='https://raw.githubusercontent.com/sak1b0/proteiNN/master/test_formatted.csv'

df_train=pd.read_csv(url_train,header=None)
df_test=pd.read_csv(url_test,header=None)


df_train=np.asarray(df_train)
df_test=np.asarray(df_test)

X_train = df_train[:, 0]
y_train = df_train[:, 1]

X_test = df_test[:, 0]
y_test = df_test[:, 1]

def debug_me():
  print(df_train.shape)
  print(X_train.shape)
  print(y_train.shape)

  print(df_test.shape)
  print(X_test.shape)
  print(y_test.shape)

debug_me()

#print(len(X_train[13][0]))

max_length_train=0
dumm='shovon'
for item in range (len(X_train)):
  if(len(X_train[item])>len(dumm)):
    dumm=X_train[item]
  max_length_train=max(max_length_train,len(X_train[item]))
  
  
print('Maximum length of train: ',max_length_train)
print(dumm)

max_length_test=0
for item in range (len(X_test)):
  max_length_test=max(max_length_test,len(X_test[item]))
  
print('Maximum length of test: ',max_length_test)


#print(X_train[0])
#print(X_train[0][0].replace('H','1'))
s=X_train[0]
#no. of unique letters (there goes my label encoding)
len(list(set(s)))

data = ''

for item in range (len(X_train)):
  X_train[item] = X_train[item]+'Z'*(max_length_train-len(X_train[item]))
  data = data + X_train[item]

for item in range (len(X_train)):
  y_train[item] = y_train[item]+'Z'*(max_length_train-len(y_train[item]))
  data = data + y_train[item]
  
print(X_train[0])


print(y_train[0])

(4590, 2)
(4590,)
(4590,)
(1199, 2)
(1199,)
(1199,)
Maximum length of train:  1303
GLVPRGSHMMEILRGSPALSAFRINKLLARFQAANLQVHNIYAEYVHFADLNAPLNDSEQAQLTRLLQYGPALSSHTPAGKLLLVTPRPGTISPWSSKATDIAHNCGLQQVDRLERGVAYYIEASTLTAEQWRQVAAELHDRMMETVFSSLTDAEKLFIHHQPAPVSSVDLLGEGRQALIDANLRLGLALAEDEIDYLQEAFTKLGRNPNDIELYMFAQANSEHCRHKIFNADWIIDGKPQPKSLFKMIKNTFETTPDYVLSAYKDNAAVMEGSAVGRYFADHNTGRYDFHQEPAHILMKVETHNHPTAISPWPGAATGSGGEIRDEGATGRGAKPKAGLVGFSVSNLRIPGFEQPWEEDFGKPERIVTALDIMTEGPLGGAAFNNEFGRPALTGYFRTYEEKVNSHNGEELRGYHKPIMLAGGIGNIRADHVQKGEIVVGAKLIVLGGPAMNIGLGGGAASSMASGQSDADLDFASVQRDNPEMERRCQEVIDRCWQLGDANPILFIHDVGAGGLSNAMPELVSDGGRGGKFELRDILSDEPGMSPLEIWCNESQERYVLAVAADQLPLFDELCKRERAPYAVIGDATEEQHLSLHDNHFDNQPIDLPLDVLLGKTPKMTRDVQTLKAKGDALNRADITIADAVKRVLHLPTVAEKTFLVTIGDRTVTGMVARDQMVGPWQVPVADCAVTTASLDSYYGEAMSIGERAPVALLDFAASARLAVGEALTNIAATQIGDIKRIKLSANWMAAAGHPGEDAGLYDAVKAVGEELCPQLGLTIPVGKDSMSMKTRWQEGNEQREMTSPLSLVISAFARVEDVRHTLTPQLSTEDNALLLIDLGKGHNALGATALAQVYRQLGDKPADVRDVAQLKGFYDAMQALVAARKLLAWHDRSDGGLLVTLAEMAFAGHCGVQVDI

In [0]:
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
# define example
x_values = array(X_train)
y_values = array(y_train)
print(x_values)
print(y_values)

['RTNQAGLELIGNAEGCRRDPYMCPAGVWTDGIGNTHGVTPGVRKTDQQIAADWEKNILIAERCINQHFRGKDMPDNAFSAMTSAAFNMGCNSLRTYYSKARGMRVETSIHKWAQKGEWVNMCNHLPDFVNSNGVPLRGLKIRREKERQLCLTGLVNEHHHHHHZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ

In [0]:
# integer encode
label_encoder = LabelEncoder()
x_integer_encoded = label_encoder.fit_transform(x_values)
y_integer_encoded = label_encoder.fit_transform(y_values)
print(x_integer_encoded)
print(y_integer_encoded)

[3907  236  195 ...  325 3447  415]
[ 769  195 3435 ... 2737 1955 1991]


In [0]:
# binary encode
onehot_encoder = OneHotEncoder(sparse=False)
x_integer_encoded = integer_encoded.reshape(len(x_integer_encoded), 1)
y_integer_encoded = integer_encoded.reshape(len(y_integer_encoded), 1)

x_onehot_encoded = onehot_encoder.fit_transform(x_integer_encoded)
y_onehot_encoded = onehot_encoder.fit_transform(y_integer_encoded)

print(x_onehot_encoded)
print(y_onehot_encoded)

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a Lab

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [0]:
# invert first example
x_inverted = label_encoder.inverse_transform([argmax(x_onehot_encoded[0, :])])
print(x_inverted)
y_inverted = label_encoder.inverse_transform([argmax(y_onehot_encoded[0, :])])
print(y_inverted)

print(x_onehot_encoded.shape)
print(y_onehot_encoded.shape)

['XXXXXXXXXXXXCCHHHHHHHHHHHHHCCCCHHHHHHCCCEEECCCCCCCCCCCCCECCCCHHHHHHHHHHHHHHCCCCCHHHHHHHHHHHHHHHHHHHHHCCECCCCCCCCCCCCCCCCCCECHHHHHHHHHHHHHHHHHHHCCCCCCCCCCCCCCCCHHHHHHHHHHHHHHHHHHCCCCCEECCEEHHHHHHHHHHHCCCCCCHHHCEEECCCCCCCCCCCCCCCHHHCCCEEEEHHHHHHHHHCCCCHHHHHECCCHHHHHCCCCCCCHHHCCCECCCCCHHHHHHHHHCCCCCCECCHHHHCCCCCCEEEECHHHHHHHHHHHHHCCCCCCCHHHHHHHHHHHHHHHHHHHCHHHHHHCCHHHHHHHCCCCCCCCCCCCCHHHHHHHHHHHHHHHHCCCCCCCHHHHHHHHHCCCCCCCCCCCCCCCCCECCHHHHHHCHHHHHHHHHHHHCCCCCCCCCCHHHCZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ

In [0]:
data = np.array(x_onehot_encoded, dtype=object)
target = np.array(y_onehot_encoded, dtype=object)

print(data.shape)
print(target.shape)

(4590, 4587)
(4590, 4587)


In [0]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

Using TensorFlow backend.


In [0]:
train_x, test_x, train_y, test_y = train_test_split(data,target,test_size=0.2,random_state=4)

model = Sequential()

model.add(LSTM((1),batch_input_shape=(None,None,1),return_sequence=True))

model.compile(loss='mean_absolute_error',optimizer='adam',metrics=['accuracy'])

model.summary()

TypeError: ignored