<a href="https://colab.research.google.com/github/sak1b0/proteiNN/blob/master/life_savior.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder(handle_unknown='ignore')
s1='shovon'
max_len=10
s1=s1+'z'*(max_len-len(s1))
print(s1)

import pandas as pd
import numpy as np

url_train='https://raw.githubusercontent.com/sak1b0/proteiNN/master/train_formatted.csv'
url_test='https://raw.githubusercontent.com/sak1b0/proteiNN/master/test_formatted.csv'

df_train=pd.read_csv(url_train,header=None)
df_test=pd.read_csv(url_test,header=None)


df_train=np.asarray(df_train)
df_test=np.asarray(df_test)

X_train = df_train[:,0]
y_train = df_train[:,1]
print(X_train[0])
print(y_train[0])


shovonzzzz
RTNQAGLELIGNAEGCRRDPYMCPAGVWTDGIGNTHGVTPGVRKTDQQIAADWEKNILIAERCINQHFRGKDMPDNAFSAMTSAAFNMGCNSLRTYYSKARGMRVETSIHKWAQKGEWVNMCNHLPDFVNSNGVPLRGLKIRREKERQLCLTGLVNEHHHHHH
CCCHHHHHHHCCHHHHHHCHHHCCHHHCCCCCCCXXCCCCCCCCCHHHHHHHHHHHHHHHHHHHHHHCCHHHCCHHHHHHHHHHHHHHCHHHHHEEEECCCCEEEECHHHHHHHCCCHHHHHHCHHHCCEECCEECHHHHHHHHHHHHHHHCCCCCCXXXXXC


try to find if it actually works or not :p

In [0]:
from sklearn.preprocessing import MultiLabelBinarizer
#print(X_train[0])
#abcdefghijklmnopqrstuvwxyz
x='aabcz'
print(len(x))
one_hot = MultiLabelBinarizer()
x=one_hot.fit_transform(x)
print(x)
print(x.shape)
print(len(x))
print('before proceeding do as much experiments shovon, if we mess up here we doomed :p ')




5
[[1 0 0 0]
 [1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
(5, 4)
5
before proceeding do as much experiments shovon, if we mess up here we doomed :p 


In [0]:
dummy=['aaabaaacd','mnop']

print('length of dummy: ',len(dummy))
#for item in range(len(dummy)):
  #dummy[item]=one_hot.fit_transform(dummy[item])
dummy=one_hot.fit_transform(dummy)  
display(dummy)

print('\nnow see the difference\n')

dummy=['aaaabaaacd','mnop']
for item in range(len(dummy)):
  dummy[item]=one_hot.fit_transform(dummy[item])
 
display(dummy)




length of dummy:  2


array([[1, 1, 1, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 1, 1, 1]])


now see the difference



[array([[1, 0, 0, 0],
        [1, 0, 0, 0],
        [1, 0, 0, 0],
        [1, 0, 0, 0],
        [0, 1, 0, 0],
        [1, 0, 0, 0],
        [1, 0, 0, 0],
        [1, 0, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1]]), array([[1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1]])]